name: Contracts Line Counter

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Contracts Line Counter
      uses: javiesses/line-counter-contracts@v1
      id: custom
      
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp-relay.sendinblue.com
        server_port: 587
        username: ${{secrets.MAIL_SENDER_USERNAME}}
        password: ${{secrets.MAIL_SENDER_PASSWORD}}
        subject: New commit on main branch
        to: ${{secrets.MAIL_TO}}
        from: Your Olympix Assistant <${{secrets.MAIL_SENDER_USERNAME}}>
        body: ${{ steps.custom.outputs.html }}